git:
  fetchAll: false
  paging:
    colorArg: always
    pager: delta --dark --paging=never

gui:
  nerdFontsVersion: "3"
  showFileIcons: true
  showDivergenceFromBaseBranch: onlyArrow

os:
  editPreset: nvim

customCommands:
  - key: p
    command: >-
      {{$branch := .CheckedOutBranch.Name}}
      git fetch origin {{$branch}} --prune --prune-tags
      && git rebase origin/{{$branch}} {{$branch}}
    context: global
    description: Fetch and update current branch
    showOutput: true
  - key: p
    command: >-
      {{$branch := .SelectedLocalBranch.Name}}
      git fetch origin {{$branch}} --prune --prune-tags
      && git rebase origin/{{$branch}} {{$branch}}
    context: localBranches
    description: Fetch and update branch
    showOutput: true
