git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  fetchAll: false
nerdFontsVersion: 3
showFileIcons: true
showDivergenceFromBaseBranch: onlyArrow
os:
  editPreset: nvim

customCommands:
  - key: p
    command: "git fetch origin {{.CheckedOutBranch.Name}} --prune --prune-tags"
    context: global
    description: Fetch and update branch
